root: true

parser: babel-eslint

plugins:
  - react

env:
  browser: true
  node: true

rules:
  # Possible Errors
  no-constant-condition: [error, {checkLoops: false}]
  no-unexpected-multiline: error

  # Best Practices
  block-scoped-var: warn
  eqeqeq: warn
  no-alert: off
  no-eq-null: error
  no-floating-decimal: warn
  radix: warn
  wrap-iife: warn

  # Strict Mode
  strict: off

  # Variables
  no-use-before-define: [error, nofunc]

  # Stylistic Issues
  array-bracket-spacing: [error, never]
  brace-style: [error, 1tbs]
  camelcase: [warn, {properties: never}]
  comma-dangle: [warn, {arrays: always-multiline,
                        objects: always-multiline,
                        imports: always-multiline,
                        exports: always-multiline,
                        functions: always-multiline}]
  consistent-this: [warn, self]
  indent: [error, 2, {SwitchCase: 1}]
  jsx-quotes: [error, prefer-double]
  keyword-spacing: [error, {before: true, after: true}]
  linebreak-style: [error, unix]
  new-cap: off
  no-lonely-if: warn
  no-multiple-empty-lines: [warn, {max: 2}]
  no-underscore-dangle: off
  no-unneeded-ternary: warn
  object-curly-spacing: [error, never]
  padded-blocks: [error, never]
  quote-props: [warn, as-needed]
  quotes: [warn, single, {avoidEscape: true,
                          allowTemplateLiterals: true}]
  space-before-blocks: [error, always]
  space-before-function-paren: [error, {anonymous: always,
                                        named: never,
                                        asyncArrow: always}]
  spaced-comment: [warn, always]

  #######################
  # eslint-plugin-react #
  #######################

  react/boolean-prop-naming: off
  react/button-has-type: error
  react/default-props-match-prop-types: off
  react/destructuring-assignment: off
  react/display-name: off
  react/forbid-component-props: off
  react/forbid-dom-props: off
  react/forbid-elements: off
  react/forbid-prop-types: off
  react/forbid-foreign-prop-types: off
  react/no-access-state-in-setstate: error
  react/no-array-index-key: off
  react/no-children-prop: error
  react/no-danger: off
  react/no-danger-with-children: error
  react/no-deprecated: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: warn
  react/no-is-mounted: warn
  react/no-multi-comp: [warn, {ignoreStateless: true}]
  react/no-redundant-should-component-update: error
  react/no-render-return-value: warn
  react/no-set-state: warn
  react/no-typos: error
  react/no-string-refs: warn
  react/no-this-in-sfc: error
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/no-unused-prop-types: off
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-es6-class: off
  react/prefer-stateless-function: warn
  react/prop-types: off
  react/react-in-jsx-scope: error
  react/require-default-props: off
  react/require-optimization: off
  react/require-render-return: error
  react/self-closing-comp: error
  react/sort-comp: warn
  react/sort-prop-types: off
  react/style-prop-object: error
  react/void-dom-elements-no-children: error

  # JSX-specific rules
  react/jsx-boolean-value: [warn, never]
  react/jsx-closing-bracket-location: [error, tag-aligned]
  react/jsx-closing-tag-location: error
  react/jsx-curly-spacing: [error, {when: never}]
  react/jsx-equals-spacing: [error, never]
  react/jsx-filename-extension: [error, {extensions: [.js]}]
  react/jsx-first-prop-new-line: [error, multiline-multiprop]
  react/jsx-handler-names: warn
  react/jsx-indent: [error, 2]
  react/jsx-indent-props: [error, 2]
  react/jsx-key: warn
  react/jsx-max-props-per-line: [error, {maximum: 1, when: multiline}]
  react/jsx-no-bind: warn
  react/jsx-no-comment-textnodes: warn
  react/jsx-no-duplicate-props: [error, {ignoreCase: true}]
  react/jsx-no-literals: warn
  react/jsx-no-target-blank: error
  react/jsx-no-undef: [error, {allowGlobals: true}]
  react/jsx-one-expression-per-line: off
  react/jsx-curly-brace-presence: [error, {props: never, children: ignore}]
  react/jsx-pascal-case: error
  react/jsx-sort-default-props: warn
  react/jsx-sort-props: warn
  react/jsx-tag-spacing: [error, {beforeClosing: never}]
  react/jsx-uses-react: warn
  react/jsx-uses-vars: warn
  react/jsx-wrap-multilines: [error, {declaration: parens-new-line,
                                      assignment: parens-new-line,
                                      return: parens-new-line,
                                      arrow: parens-new-line,
                                      condition: parens-new-line,
                                      logical: parens-new-line,
                                      prop: ignore}]
