rules:
  no-await-in-loop: error
  consistent-return: error
  eqeqeq: [warn, smart]
  wrap-iife: warn
  camelcase: [warn, {properties: never,
                     allow: [
                       "l_attributes",
                       "ln_attributes",
                       "lp_attributes",
                       "l_countries",
                       "ln_countries",
                       "lp_countries",
                       "l_instrument_descriptions",
                       "ln_instrument_descriptions",
                       "lp_instrument_descriptions",
                       "l_instruments",
                       "ln_instruments",
                       "lp_instruments",
                       "l_languages",
                       "ln_languages",
                       "lp_languages",
                       "l_relationships",
                       "ln_relationships",
                       "lp_relationships",
                       "l_scripts",
                       "ln_scripts",
                       "lp_scripts",
                       "l_statistics",
                       "ln_statistics",
                       "lp_statistics",
                       "N_l",
                       "N_ln",
                       "N_lp",
                     ]}]
  comma-spacing: [warn, {before: false, after: true}]
  computed-property-spacing: [warn, never, {"enforceForClassMembers": true}]
  consistent-this: [warn, self]
  jsx-quotes: [warn, prefer-double]
  key-spacing: [warn, {mode: minimum}]
  newline-per-chained-call: [warn, {ignoreChainWithDepth: 3}]
  no-lonely-if: warn
  object-curly-newline: [warn, {multiline: true, consistent: true}]
  object-curly-spacing: [warn, never]
  operator-assignment: [warn, always]
  operator-linebreak: [warn, after, {overrides: {?: before, :: before}}]
  padded-blocks: [warn, never]
  quote-props: [warn, consistent-as-needed, {numbers: true}]
  quotes: [warn, single, {avoidEscape: true,
                          allowTemplateLiterals: true}]
  semi: [warn, always, {omitLastInOneLineBlock: true}]
  semi-style: [warn, last]
  sort-keys: [warn, asc, {caseSensitive: false, natural: true}]
  space-before-function-paren: [warn, {anonymous: always,
                                       named: never,
                                       asyncArrow: always}]
  space-infix-ops: [warn, {int32Hint: true}]
  no-var: warn
  prefer-const: warn
  import/first: warn
  import/no-commonjs: error
  import/order: [warn, {newlines-between: always}]
  react/no-access-state-in-setstate: error
  react/no-multi-comp: [warn, {ignoreStateless: true}]
  react/no-render-return-value: warn
  react/prefer-stateless-function: warn
  react/self-closing-comp: error
  react/sort-comp: [warn, {order: [type-annotations,
                                   static-methods,
                                   lifecycle,
                                   everything-else,
                                   render]}]
  react/jsx-closing-bracket-location: [error, tag-aligned]
  react/jsx-first-prop-new-line: [error, multiline-multiprop]
  react/jsx-key: warn
  react/jsx-no-bind: [warn, {ignoreDOMComponents: true}]
  react/jsx-no-literals: warn
  react/jsx-sort-props: warn
  flowtype/boolean-style: [warn, boolean]
  flowtype/delimiter-dangle: [warn, always-multiline]
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-weak-types: warn
  flowtype/sort-keys: [warn, asc]
  react-hooks/exhaustive-deps: warn
