---
abstract: ~
author:
  - 'Oliver Charles'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  XML::Parser: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: musicbrainz
no_index:
  directory:
    - inc
    - t
recommends:
  Apache::Session: 0
  Apache::Session::File: 0
requires:
  Algorithm::Diff: 1.1902
  Cache: 2.04
  Cache::Memcached: 1.24
  Cache::Memcached::Fast: 0.16
  Catalyst::Action::RenderView: 0.09
  Catalyst::Authentication::Credential::HTTP: 1.009
  Catalyst::Component::ACCEPT_CONTEXT: 0.06
  Catalyst::Model::Factory: 0.03
  Catalyst::Plugin::Authentication: 0.10011
  Catalyst::Plugin::Cache::HTTP: 0
  Catalyst::Plugin::ConfigLoader: 0.24
  Catalyst::Plugin::I18N: 0.09
  Catalyst::Plugin::Session::State::Cookie: 0.11
  Catalyst::Plugin::Session::Store::FastMmap: 0.07
  Catalyst::Plugin::StackTrace: 0.09
  Catalyst::Plugin::Static::Simple: 0.21
  Catalyst::Runtime: 5.80007
  Catalyst::View::TT: 0.29
  DBD::Pg: 2.11.8
  DBI: 1.607
  Data::Page: 2.01
  Date::Calc: 5.4
  DateTime::Format::Pg: 0.16004
  DateTime::TimeZone: 0
  Devel::Peek: 1.03
  Digest::MD5: 2.39
  Digest::SHA1: 2.110
  Email::Address: 0
  Email::Date::Format: 1.002
  Email::MIME: 0
  Email::MIME::Creator: 0
  Email::Sender: 0
  Email::Valid: 0.179
  Exception::Class: 1.29
  HTML::FormHandler: 0.27
  HTML::Tiny: 1.05
  JSON: 2.14
  List::MoreUtils: 0.22
  Locale::Maketext: 1.12
  Locale::Maketext::Extract::Plugin::TT2: 0
  Locale::TextDomain: 1.16
  MIME::Lite: 3.023
  MRO::Compat: 0.10
  Moose: 0.87
  MooseX::AttributeHelpers: 0.17
  MooseX::MethodAttributes: 0.14
  MooseX::Role::Parameterized: 0.10
  MooseX::Storage: 0.150
  MooseX::Types: 0.16
  MooseX::Types::Structured: 0.16
  OSSP::uuid: 1.060200
  Readonly: 1.03
  String::ShellQuote: 1.030
  String::Similarity: 1.030
  Text::Unaccent: 1.080
  Text::WikiFormat: 0.790
  TryCatch: 0
  XML::Feed: 0.410
  XML::Simple: 2.18
  YAML: 0.680
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
